### ISSUE TITLE
Alpha / Beta improvements To-Do List

### ISSUE THREAD

**Issue by Indra-db** [Indra-db/flecs-ecs-rs#19]
This list contains mainly two things:
* Functions that were overlooked during core development
* Places discovered where the API needs improvement
---------------------------------------------------------------------------------------------

- [x] Support const component evaluation w/ filter, query, system
- [x] Implement missing `find` function on query & filter
- [x] Implement missing `.each_iter` which passes iter and index on Filter, Query, System, Observer
- [x] Implement missing iter_iterable class (see example group_iter in queries cpp)
- [x] implement entity_builder.observer functionality (with and without payload) from 3.2.11
- [x] clean up and simplify registering components
- [x] support templated components
- [x] v4 upgrade + refactor term

extra:
- [x] added rules addon

### API Improvements
- [ ] (blocked) Improve query_builder::group_by_fn, system_builder:{:set_run_callback,order_by} API to support rust closures instead of extern "C" functions -> blocked by flecs_core not having support for this at the moment.
- [x] align and improve function naming
- [x] Filter, Query, system, observer cleanup
- [x] refactor API and replace _pair functions and overload to allow u64, Entity, EntityView, etc. 
- [x] add attribute macro to make manual template implementation easier -> register attribute

**Comment by Indra-db** [comment]
finished.
